### ISSUE TITLE
请问跨天的日程结束时间总是少显示一天是怎么回事呢？

### ISSUE THREAD

**Issue by sjlei** [a306916069/vue-lunar-fullcalendar#14]
如图所示，在未对组件进行任何配置的情况下，我添加了一个日程，开始时间是 `2019-9-17`，结束时间是 `2019-9-20`

![image](https://user-images.githubusercontent.com/34293221/65517504-67c85400-df15-11e9-9355-91a6beda72a3.png)

但是实际显示的时候就有问题了，可以看到20号那天没有显示

![image](https://user-images.githubusercontent.com/34293221/65517597-921a1180-df15-11e9-8737-5ae1d616e844.png)

检查了下传递过去了 events，也没有问题

![image](https://user-images.githubusercontent.com/34293221/65517939-153b6780-df16-11e9-9d2e-fc032116534c.png)

请问这是什么问题呢？

**Comment by a306916069** [comment]
options.nextDayThreshold&nbsp; 查下这个属性，应该能解决你的问题




---原始邮件---
发件人: "牧星长"<notifications@github.com&gt;
发送时间: 2019年9月24日(星期二) 晚上9:57
收件人: "a306916069/vue-lunar-fullcalendar"<vue-lunar-fullcalendar@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [a306916069/vue-lunar-fullcalendar] 请问跨天的日程结束时间总是少显示一天是怎么回事呢？ (#14)



如图所示，在未对组件进行任何配置的情况下，我添加了一个日程，开始时间是 2019-9-17，结束时间是 2019-9-20
 

 
但是实际显示的时候就有问题了，可以看到20号那天没有显示
 

 
检查了下传递过去了 events，也没有问题
 

 
请问这是什么问题呢？

**Comment by sjlei** [comment]
刚刚试了下，还是不行，真的太奇怪了，设置了 `nextDayThreshold` :`00:00:00`还不行，

![image](https://user-images.githubusercontent.com/34293221/65563885-a265d700-df7d-11e9-9407-b23edc66038c.png)

被逼无奈我把结束时间都设置成 `2019-09-20 23:59:59` 了还是不行😭

![image](https://user-images.githubusercontent.com/34293221/65563625-c70d7f00-df7c-11e9-8275-c5ccdbb021fb.png)

**Comment by sjlei** [comment]
研究了下发现，`nextDayThreshold` 对全天事件不生效。。。 全天的结束时间改成图中那样居然就好了= =

![image](https://user-images.githubusercontent.com/34293221/65566409-5159e100-df85-11e9-8102-37e47e56c7ff.png)
