### ISSUE TITLE
怎么把右边的按钮换成中文的，还有不想要农历

### ISSUE THREAD

**Issue by jiazhuangzhexiaozhang** [a306916069/vue-lunar-fullcalendar#3]

**Comment by a306916069** [comment]
更新vue-lunar-full-calendar版本到1.2.2里面config属性有个lunarCalendar设置为false即可去掉农历，locale: 'zh-cn' 可设置为中文，至于按钮设置为中文的你拉下最新代码，看下里面代码lunarFullCalendar.vue就知道怎么弄了。

**Comment by jiazhuangzhexiaozhang** [comment]
就是按钮问题就算换成中文的也没用啊！是需要去改js代码吗！

**Comment by a306916069** [comment]
？？？你是要捕获点击切换时候的事件

**Comment by a306916069** [comment]
https://fullcalendar.io/docs  一些细节功能属性介绍你可以去看这个文档，我是根据这个封装成vue的。可以去看下  customButtons ，header,buttonTest的使用，应该能找到你要的答案。
